### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by alexiusp**
I propose these changes to make this plugin work also on windows machines

### CODE REVIEW

**Comment by BR0kEN-** [comment]
Thanks for your contribution, @alexiusp. I'm ready to merge the PR if you're fine with additional changes I made.

**Review by BR0kEN- — APPROVED** [review]

**Comment by alexiusp** [comment]
Yes, sure, looks much better!

**Comment by alexiusp** [comment]
is some action required from my side? I'm not used to GitHub workflow, sorry.

**Comment by francesko** [comment]
Thanks for the fix guys! Could you please also release a new version to packagist, I don't get the changes via composer install.

**Comment by BR0kEN-** [comment]
Oh wow, @francesko - that's definitely a good point I completely forgot about. Now it's done. Thanks.

**Comment by francesko** [comment]
Great, thank you @BR0kEN-.

**Pull request merged**
